image: node:14

stages:
  - test
  - deploy

variables:
  CI_DEBUG_TRACE: "false"  # Enable debug mode for CI debugging if needed

# No need to cache or install dependencies since we're not building again

# build:
#   stage: build
#   script:
#     - npm install  # Install dependencies
#     - npm run build  # Build the React application
#   artifacts:
#     paths:
#       - build/  # Archive the build directory for deployment

deploy:
  stage: deploy
  script:
    - npm install -g gh-pages  # Install gh-pages globally
    - npm run deploy  # Deploy the application to GitHub Pages
  dependencies: []  # No dependencies as we're not building
  only:
    - master  # Deploy only when changes are pushed to master branch
