image: node:14

stages:
  - test
  - deploy

variables:
  CI_DEBUG_TRACE: "false"  # Enable debug mode for CI debugging if needed

before_script:
  - npm install -g gh-pages  # Install gh-pages globally
  - npm install  # Install project dependencies

deploy:
  stage: deploy
  script:
    - npm run build  # Build the React application
    - mv build public  # Rename build folder to public to deploy to GitHub Pages
    - gh-pages -d public -b master  # Deploy the application to GitHub Pages
  only:
    - master  # Deploy only when changes are pushed to master branch
